server:
  port: 8087
spring:
  services:
    tech-card:
      host: localhost:8087
  flyway:
    locations: classpath:/db/migration
    schemas: warehouse
  main:
    allow-bean-definition-overriding: true

  datasource:
    #        url: jdbc:postgresql://tech-card-service_postgres_1:5432/erp
    url: jdbc:postgresql://localhost:5432/erp
    username: postgres
    password: postgres
    #    driver-class-name: org.postgresql.Driver

    hikari:
      minimum-idle: 0
      initialization-fail-timeout: -1
      schema: warehouse

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

